backend:
    build: backend
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
  database:
    environment:
      - POSTGRES_PASSWORD=secret
    healthcheck:
      interval: 2s
      test: "pg_isready --username=postgres"
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
  frontend:
    build: frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
